from typing import TypedDict, List, Dict, Any, Optional
from langgraph.graph import StateGraph, END

from agents import (
    data_ingestion,
    customer_feedback,
    market_research,
    swot_analysis,
    feature_prioritization,
    strategy_recommendation,
    executive_report,
)


class AgentState(TypedDict, total=False):
    # Input
    parsed_files: List[Dict]
    data_context: str
    user_query: Optional[str]

    # Agent outputs
    ingestion_status: str
    ingestion_complete: bool
    num_chunks: int
    customer_insights: str
    market_research: str
    swot_analysis: str
    opportunity_assessment: str
    feature_prioritization: str
    strategy_recommendations: str
    executive_summary: str
    key_metrics: Dict[str, str]

    # Control
    pipeline_complete: bool
    current_agent: str
    agent_logs: List[str]


AGENT_SEQUENCE = [
    ("Data Ingestion Agent", "Parsing files and indexing into vector store...", data_ingestion.run),
    ("Customer Feedback Agent", "Analyzing customer reviews and sentiment patterns...", customer_feedback.run),
    ("Market Research Agent", "Evaluating market trends and regional performance...", market_research.run),
    ("SWOT Analysis Agent", "Synthesizing SWOT and opportunity assessment...", swot_analysis.run),
    ("Feature Prioritization Agent", "Scoring and prioritizing product improvements...", feature_prioritization.run),
    ("Strategy Recommendation Agent", "Generating strategic action plan and roadmap...", strategy_recommendation.run),
    ("Executive Report Agent", "Compiling executive summary and final report...", executive_report.run),
]


def build_graph() -> StateGraph:
    graph = StateGraph(AgentState)

    def make_node(agent_fn):
        def node_fn(state: AgentState) -> AgentState:
            return agent_fn(state)
        return node_fn

    prev = None
    for name, _, fn in AGENT_SEQUENCE:
        safe_name = name.lower().replace(" ", "_")
        graph.add_node(safe_name, make_node(fn))
        if prev:
            graph.add_edge(prev, safe_name)
        else:
            graph.set_entry_point(safe_name)
        prev = safe_name

    graph.add_edge(prev, END)
    return graph.compile()


def run_pipeline(parsed_files: List[Dict], data_context: str, user_query: str = "", progress_callback=None) -> Dict:
    """
    Run the full multi-agent pipeline.
    progress_callback(agent_name, description, step, total) is called before each agent runs.
    Returns the final state dict.
    """
    app = build_graph()

    initial_state: AgentState = {
        "parsed_files": parsed_files,
        "data_context": data_context,
        "user_query": user_query,
        "agent_logs": [],
        "pipeline_complete": False,
    }

    total = len(AGENT_SEQUENCE)

    if progress_callback:
        # Stream step by step using individual agent calls for progress visibility
        state = dict(initial_state)
        for i, (name, desc, fn) in enumerate(AGENT_SEQUENCE):
            progress_callback(name, desc, i + 1, total)
            state = fn(state)
        return state
    else:
        result = app.invoke(initial_state)
        return result


def run_chat_query(question: str, state: Dict) -> str:
    """Answer a follow-up question using the accumulated agent context."""
    from utils.llm_client import get_client

    client = get_client()

    context_parts = []
    for key, label in [
        ("customer_insights", "Customer Insights"),
        ("market_research", "Market Research"),
        ("swot_analysis", "SWOT Analysis"),
        ("opportunity_assessment", "Opportunity Assessment"),
        ("feature_prioritization", "Feature Prioritization"),
        ("strategy_recommendations", "Strategy Recommendations"),
        ("executive_summary", "Executive Summary"),
    ]:
        val = state.get(key, "")
        if val:
            context_parts.append(f"=== {label} ===\n{val[:600]}")

    context = "\n\n".join(context_parts)

    system = """You are an AI Product Strategy Assistant. You have access to comprehensive analyses
generated by a team of specialized AI agents. Answer questions accurately and specifically,
referencing data from the analyses. Be concise and actionable."""

    prompt = f"""Based on the following strategic analyses, answer this question:

QUESTION: {question}

AVAILABLE ANALYSES:
{context}

Provide a specific, data-backed answer. If the question asks about something not covered in the analyses,
say so clearly and suggest what additional data would help."""

    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {"role": "system", "content": system},
            {"role": "user", "content": prompt},
        ],
        temperature=0.4,
        max_completion_tokens=500,
    )
    return response.choices[0].message.content
